version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies & build
          command: |
            apt update && apt install -y curl git
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
            source $HOME/.nvm/nvm.sh && \
            nvm install v14.20.1 && nvm use v14.20.1 && \
            npm install && npm run build
            cp ./dist/kids-landing/index.html ./dist/kids-landing/404.html
            mv ./deploy/CNAME ./dist/kids-landing/CNAME

      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  deploy:
    docker:
      - image: node:12.14
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages
            git config --global user.email "ci@ponddy-edu.com"
            git config --global user.name "ponddy-edu"

      - add_ssh_keys:
          fingerprints:
            - "c6:d4:76:5a:50:d5:6b:6a:aa:fb:9b:a7:05:10:76:b1"

      - run:
          name: Deploying
          command: |
            export MSG="#${CIRCLE_BUILD_NUM} ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} is updating"
            curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"text":"'"${MSG}"'"}' \
            "${SLACK_WEBHOOK}"
            gh-pages --dist=dist/kids-landing --message "[skip ci] Updates GitHub page $CIRCLE_SHA1" --no-history
            # Deployed
            export MSG="#${CIRCLE_BUILD_NUM} ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} is updated"
            curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"text":"'"${MSG}"'"}' \
            "${SLACK_WEBHOOK}"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          context:
            - slack
          filters:
            branches:
              only:
                - main
